# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .iothub_registry_manager import IoTHubRegistryManager

__path__ = __import__("pkgutil").extend_path(__path__, __name__)
__all__ = ['IoTHubRegistryManager']

